### ISSUE TITLE
Request: GPU Offloading for Compress/Decompress

### ISSUE THREAD

**Issue by iamhumanipromise** [chemfiles/lzma#2]
Requesting the ability to utilize any OpenCL device for decompression. (Or Any ROCM/HIP, CUDA, or OneAPI/Level Zero supported device if that is not an option.

**Comment by Luthaf** [comment]
Hello, this is not the official LZMA repository, but a fork for internal usage in https://github.com/chemfiles/chemfiles. 
You'll want to discuss about GPU support in the official repository: https://github.com/tukaani-project/xz, or contact the developers https://tukaani.org/contact.html
